STRINGS = {
    "appTitle": ("Nectar", "Nectar"),
    # Общие
    "cancel": ("Отмена", "Cancel"),
    "save": ("Сохранить", "Save"),
    "delete": ("Удалить", "Delete"),
    "retry": ("Повторить", "Retry"),
    "logout": ("Выйти", "Log out"),
    "logoutFromAccount": ("Выйти из аккаунта", "Log out of account"),
    "apply": ("Применить", "Apply"),
    "reset": ("Сбросить", "Reset"),
    "back": ("Назад", "Back"),
    "add": ("Добавить", "Add"),
    "genericError": ("Произошла ошибка. Попробуйте еще раз.", "Something went wrong. Please try again."),
    "saveFailed": ("Не удалось сохранить. Попробуйте еще раз.", "Could not save. Please try again."),
    "loadFailedCheckConnection": ("Не удалось загрузить данные. Проверьте соединение.", "Could not load data. Check your connection."),
    "loadFailedTryLater": ("Не удалось загрузить данные. Попробуйте позже.", "Could not load data. Please try later."),
    "notEnoughStock": ("Больше нет в наличии", "No more items in stock"),
    "language": ("Язык", "Language"),
    "languageRussian": ("Русский", "Russian"),
    "languageEnglish": ("English", "English"),
    "selectLanguage": ("Выберите язык", "Choose language"),
    # Навигация
    "navShop": ("Магазин", "Shop"),
    "navCatalog": ("Каталог", "Catalog"),
    "navCart": ("Корзина", "Cart"),
    "navProfile": ("Профиль", "Profile"),
    # Роли
    "roleAdmin": ("Администратор", "Administrator"),
    "roleManager": ("Менеджер", "Manager"),
    "roleCourier": ("Курьер", "Courier"),
    "roleBuyer": ("Покупатель", "Customer"),
    "roleGuest": ("Гость", "Guest"),
    # Валидаторы
    "valLoginRequired": ("Введите логин", "Enter your login"),
    "valLoginLength": ("Длина логина от 3 до 50 символов", "Login must be 3 to 50 characters long"),
    "valLoginChars": ("Только латиница, цифры и символы ._-", "Latin letters, digits and ._- only"),
    "valFieldRequired": ("Поле не может быть пустым", "This field cannot be empty"),
    "valNameLength": ("Длина от 2 до 50 символов", "Must be 2 to 50 characters long"),
    "valNameChars": ("Только буквы, пробелы и дефисы", "Letters, spaces and hyphens only"),
    "valEmailRequired": ("Введите email", "Enter your email"),
    "valEmailLength": ("Email не должен превышать 100 символов", "Email must not exceed 100 characters"),
    "valEmailFormat": ("Неверный формат email", "Invalid email format"),
    "valPhoneRequired": ("Введите номер телефона", "Enter your phone number"),
    "valPhoneFormat": ("Неверный формат номера телефона", "Invalid phone number format"),
    "valPasswordRequired": ("Введите пароль", "Enter your password"),
    "valPasswordNoSpaces": ("Пароль не должен содержать пробелы", "Password must not contain spaces"),
    "valPasswordMaxLength": ("Не более 128 символов", "At most 128 characters"),
    "valPasswordMinLength": ("Минимум 6 символов", "At least 6 characters"),
    "valPasswordDigit": ("Пароль должен содержать минимум одну цифру", "Password must contain at least one digit"),
    "valPasswordConfirmRequired": ("Подтвердите пароль", "Confirm your password"),
    "valPasswordMismatch": ("Пароли не совпадают", "Passwords do not match"),
    "valNamedFieldRequired": ("Поле «{fieldName}» обязательно", "The “{fieldName}” field is required"),
    "valNamedFieldMaxLength": ("Поле «{fieldName}» не должно превышать {maxLength:int} символов", "The “{fieldName}” field must not exceed {maxLength:int} characters"),
    "valPriceRequired": ("Введите цену", "Enter the price"),
    "valPricePositive": ("Цена должна быть больше 0", "The price must be greater than 0"),
    "valNamedValueRequired": ("Введите значение для «{fieldName}»", "Enter a value for “{fieldName}”"),
    "valNamedRange": ("Поле «{fieldName}» должно быть в диапазоне {minValue:int}-{maxValue:int}", "The “{fieldName}” field must be between {minValue:int} and {maxValue:int}"),
    "valPromoRequired": ("Введите промокод", "Enter a promo code"),
    "valPromoChars": ("Только латиница и цифры", "Latin letters and digits only"),
    "valTaxIdRequired": ("Введите ИНН", "Enter the tax ID"),
    "valTaxIdFormat": ("ИНН должен содержать 10 или 12 цифр", "Tax ID must contain 10 or 12 digits"),
    "valCardRequired": ("Введите номер карты", "Enter the card number"),
    "valCardLength": ("Номер карты должен содержать 16 цифр", "The card number must contain 16 digits"),
    # Фильтры и сортировка
    "sortDefault": ("По умолчанию", "Default"),
    "sortFreshFirst": ("Сначала свежие", "Freshest first"),
    "sortPriceDesc": ("По убыванию цены", "Price: high to low"),
    "sortPriceAsc": ("По возрастанию цены", "Price: low to high"),
    "filtersTitle": ("Фильтры", "Filters"),
    "filterPrice": ("Цена: {from:int} – {to:int} ₽", "Price: {from:int} – {to:int} ₽"),
    "filterBrand": ("Бренд", "Brand"),
    "filterSort": ("Сортировка", "Sort by"),
    "noProductsForFilters": ("Нет товаров, подходящих под выбранные фильтры", "No products match the selected filters"),
    # Доставка
    "slotAsap": ("Как можно скорее (до 60 минут)", "As soon as possible (within 60 minutes)"),
    # Товар
    "noDescription": ("Детальное описание товара отсутствует.", "No detailed description available."),
    "currencyRub": ("₽", "₽"),
    "unitKg": ("кг", "kg"),
    "unitG": ("г", "g"),
    "unitMl": ("мл", "ml"),
    "unitL": ("л", "l"),
    "unitPcs": ("шт", "pcs"),
}
