STRINGS = {
    # Авторизация
    "authInvalidEmail": ("Некорректный email.", "Invalid email address."),
    "authUserDisabled": ("Этот аккаунт отключен.", "This account has been disabled."),
    "authWrongCredentials": ("Неверный email или пароль.", "Wrong email or password."),
    "authEmailInUse": ("Этот email уже используется.", "This email is already in use."),
    "authWeakPassword": ("Пароль слишком простой.", "The password is too weak."),
    "authNetworkError": ("Не удалось подключиться к сети.", "Could not connect to the network."),
    "authTooManyRequests": ("Слишком много попыток. Попробуйте позже.", "Too many attempts. Please try later."),
    "authAccountDeleted": ("Этот аккаунт был удален.", "This account has been deleted."),
    "authNotSignedIn": ("Пользователь не авторизован.", "You are not signed in."),
    "authWrongCurrentPassword": ("Неверный текущий пароль.", "The current password is incorrect."),
    # Данные
    "errLoginTaken": ("Пользователь с таким логином уже существует.", "A user with this login already exists."),
    "errLoginNotFound": ("Пользователь с таким логином не найден.", "No user with this login was found."),
    "errAddressEmpty": ("Адрес не может быть пустым.", "The address cannot be empty."),
    "errAddressTooLong": ("Адрес не должен превышать 300 символов.", "The address must not exceed 300 characters."),
    "errCardLength": ("Номер карты должен содержать 16 цифр.", "The card number must contain 16 digits."),
    "errPromoInvalid": ("Неверный или просроченный промокод.", "Invalid or expired promo code."),
    "errCartEmpty": ("Корзина пуста.", "The cart is empty."),
    "errDeliveryAddressRequired": ("Укажите адрес доставки.", "Specify a delivery address."),
    "errPaymentMethodRequired": ("Выберите способ оплаты.", "Choose a payment method."),
    "errUserNotFound": ("Пользователь не найден.", "User not found."),
    "errQuantityPositive": ("Количество товара должно быть больше нуля.", "The quantity must be greater than zero."),
    "errProductUnavailable": ("Товар «{name}» недоступен.", "The product “{name}” is unavailable."),
    "errNotEnoughStock": ("Недостаточно товара «{name}» на складе.", "Not enough “{name}” in stock."),
    "errOrderNotFound": ("Заказ не найден.", "Order not found."),
    "errUserHasActiveOrders": ("Нельзя удалить пользователя с незавершенными заказами.", "You cannot delete a user who has unfinished orders."),
    "errCategoryNameRequired": ("Название категории обязательно.", "The category name is required."),
    "errCategoryNameTooLong": ("Название категории не должно превышать 100 символов.", "The category name must not exceed 100 characters."),
    "errCategoryDescriptionTooLong": ("Описание категории не должно превышать 500 символов.", "The category description must not exceed 500 characters."),
    "errCategoryExists": ("Категория с таким названием уже существует.", "A category with this name already exists."),
    "errCategoryNotFound": ("Категория не найдена.", "Category not found."),
    "errCategoryHasProducts": ("Нельзя удалить категорию, к которой привязаны продукты.", "You cannot delete a category that has products."),
    "errManufacturerNameRequired": ("Название производителя обязательно.", "The manufacturer name is required."),
    "errManufacturerNameTooLong": ("Название производителя не должно превышать 100 символов.", "The manufacturer name must not exceed 100 characters."),
    "errManufacturerExists": ("Производитель с таким названием уже существует.", "A manufacturer with this name already exists."),
    "errManufacturerNotFound": ("Производитель не найден.", "Manufacturer not found."),
    "errManufacturerHasProducts": ("Нельзя удалить производителя, к которому привязаны продукты.", "You cannot delete a manufacturer that has products."),
    "errSupplierNameRequired": ("Название поставщика обязательно.", "The supplier name is required."),
    "errSupplierExists": ("Поставщик с таким названием уже существует.", "A supplier with this name already exists."),
    "errSupplierNotFound": ("Поставщик не найден.", "Supplier not found."),
    "errSupplierHasSupplies": ("Нельзя удалить поставщика, если существуют активные поставки продуктов.", "You cannot delete a supplier with active product supplies."),
    "errRoleNameRequired": ("Название роли обязательно.", "The role name is required."),
    "errRoleNameTooLong": ("Название роли не должно превышать 50 символов.", "The role name must not exceed 50 characters."),
    "errRoleExists": ("Роль с таким названием уже существует.", "A role with this name already exists."),
    "errRoleHasUsers": ("Нельзя удалить роль, если к ней привязаны пользователи.", "You cannot delete a role that has users."),
    "errStatusNameRequired": ("Название статуса обязательно.", "The status name is required."),
    "errStatusNameTooLong": ("Название статуса не должно превышать 50 символов.", "The status name must not exceed 50 characters."),
    "errStatusExists": ("Статус с таким названием уже существует.", "A status with this name already exists."),
    "errStatusInUse": ("Нельзя удалить статус, который используется в заказах.", "You cannot delete a status used by orders."),
    "errPromoCodeRequired": ("Код промокода обязателен.", "The promo code is required."),
    "errPromoCodeChars": ("Промокод должен содержать только латиницу и цифры.", "The promo code must contain only Latin letters and digits."),
    "errPromoDiscountRange": ("Скидка должна быть в диапазоне от 1 до 99%.", "The discount must be between 1 and 99%."),
    "errPromoExpiryPast": ("Срок действия промокода не может быть в прошлом.", "The promo code expiry date cannot be in the past."),
    "errPromoCodeExists": ("Промокод с таким кодом уже существует.", "A promo code with this code already exists."),
    "errPromoInActiveOrders": ("Нельзя удалить промокод, который применен в незавершенных заказах.", "You cannot delete a promo code used in unfinished orders."),
    "errProductNameRequired": ("Название продукта обязательно.", "The product name is required."),
    "errProductNameTooLong": ("Название продукта не должно превышать 255 символов.", "The product name must not exceed 255 characters."),
    "errProductDescriptionTooLong": ("Описание продукта не должно превышать 2000 символов.", "The product description must not exceed 2000 characters."),
    "errProductPricePositive": ("Цена продукта должна быть больше 0.", "The product price must be greater than 0."),
    "errProductStockRange": ("Количество на складе должно быть в диапазоне 0-9999.", "The stock quantity must be between 0 and 9999."),
    "errProductNeedsCategory": ("Для продукта необходимо выбрать категорию и производителя.", "Choose a category and a manufacturer for the product."),
    "errOrderAlreadyTaken": ("Этот заказ уже взял другой курьер.", "This order has already been taken by another courier."),
    "errOrderCannotRelease": ("Заказ нельзя вернуть: он уже в пути или назначен не вам.", "The order cannot be returned: it is on the way or assigned to someone else."),
}
