STRINGS = {
    'avatarFormatError': ('Разрешены только изображения JPEG и PNG.', 'Only JPEG and PNG images are allowed.'),
    'avatarTooBig': ('Изображение слишком большое: после сжатия не более 150 КБ.', 'The image is too large: at most 150 KB after compression.'),
    'avatarUpdated': ('Аватар успешно обновлен.', 'Avatar updated.'),
    'avatarUploadFailed': ('Не удалось загрузить изображение.', 'Could not upload the image.'),
    'deleteAccountTitle': ('Удалить аккаунт?', 'Delete account?'),
    'deleteAccountBody': ('Аккаунт будет удален, если у вас нет незавершенных заказов. Это действие нельзя отменить.', 'Your account will be deleted if you have no unfinished orders. This cannot be undone.'),
    'deleteAccountRecentLogin': ('Для удаления аккаунта нужно войти в систему заново.', 'Please sign in again to delete your account.'),
    'deleteAccountFailed': ('Не удалось удалить аккаунт.', 'Could not delete the account.'),
    'noEmail': ('Нет email', 'No email'),
    'menuOrders': ('Заказы', 'Orders'),
    'menuMyDetails': ('Мои данные', 'My details'),
    'menuDeliveryAddress': ('Адрес доставки', 'Delivery address'),
    'menuPaymentMethods': ('Способы оплаты', 'Payment methods'),
    'menuPromoCodes': ('Промокоды', 'Promo codes'),
    'menuChangePassword': ('Сменить пароль', 'Change password'),
    'menuNotifications': ('Уведомления', 'Notifications'),
    'menuHelp': ('Помощь', 'Help'),
    'menuAbout': ('О приложении', 'About the app'),
    'deleteAccount': ('Удалить аккаунт', 'Delete account'),
}
