STRINGS = {
    'loginPanelAppBar': ('Вход в панель', 'Panel sign-in'),
    'loginPanelTitle': ('Вход в web-панель', 'Web panel sign-in'),
    'loginTitle': ('Вход в Nectar', 'Sign in to Nectar'),
    'loginPanelSubtitle': ('Войдите под ролью администратора или менеджера.', 'Sign in as an administrator or manager.'),
    'loginSubtitle': ('Войдите под логином или email, чтобы работать с заказами и покупками.', 'Sign in with your login or email to manage orders and shopping.'),
    'loginIdentifierLabel': ('Логин или email', 'Login or email'),
    'loginIdentifierRequired': ('Введите логин или email', 'Enter your login or email'),
    'loginIdentifierInvalid': ('Логин или email указан некорректно', 'The login or email is invalid'),
    'loginIdentifierHint': ('Например, ivan_01 или user@mail.com', 'For example, ivan_01 or user@mail.com'),
    'labelPassword': ('Пароль', 'Password'),
    'passwordHint': ('Введите пароль', 'Enter your password'),
    'forgotPasswordLink': ('Забыли пароль?', 'Forgot password?'),
    'signInToPanel': ('Войти в панель', 'Sign in to the panel'),
    'signIn': ('Войти', 'Sign in'),
    'continueWithGoogle': ('Продолжить с Google', 'Continue with Google'),
    'noAccount': ('Нет аккаунта?', "Don't have an account?"),
    'registerAction': ('Зарегистрироваться', 'Sign up'),
    'panelInfoNote': ('Покупатели и курьеры работают через мобильное приложение. Web-панель предназначена только для ролей «Администратор» и «Менеджер».', 'Customers and couriers use the mobile app. The web panel is only for the “Administrator” and “Manager” roles.'),
}
