STRINGS = {
    'checkoutSignInRequired': ('Необходимо войти в систему.', 'You need to sign in.'),
    'checkoutSelectAddress': ('Выберите адрес доставки.', 'Select a delivery address.'),
    'checkoutSelectCard': ('Для онлайн-оплаты выберите сохраненную карту.', 'Choose a saved card for online payment.'),
    'checkoutFailed': ('Не удалось оформить заказ.', 'Could not place the order.'),
    'checkoutTitle': ('Оформление заказа', 'Checkout'),
    'addAddressInProfile': ('Добавьте адрес в профиле', 'Add an address in your profile'),
    'paymentMethodTitle': ('Способ оплаты', 'Payment method'),
    'cardLabel': ('Карта', 'Card'),
    'addCardInProfile': ('Добавьте карту в профиле', 'Add a card in your profile'),
    'promoCodeLabel': ('Промокод', 'Promo code'),
    'promoNotSelected': ('Не выбран', 'Not selected'),
    'choose': ('Выбрать', 'Choose'),
    'summaryItemsTotal': ('Сумма товаров', 'Items total'),
    'placeOrder': ('Разместить заказ', 'Place order'),
    'orderSuccessTitle': ('Заказ успешно оформлен!', 'Order placed successfully!'),
    'orderSuccessBody': ('Номер заказа: {number}\nИстория заказа и дальнейшие уведомления будут доступны в профиле.', 'Order number: {number}\nThe order history and further notifications will be available in your profile.'),
    'backToShop': ('Вернуться в магазин', 'Back to the shop'),
}
