STRINGS = {
    'courierUpdateFailed': ('Не удалось обновить заказ. Попробуйте еще раз.', 'Could not update the order. Please try again.'),
    'courierNotSignedIn': ('Курьер не авторизован.', 'The courier is not signed in.'),
    'courierTitle': ('Доставка', 'Delivery'),
    'courierNoOrders': ('У вас пока нет назначенных заказов.', 'You have no assigned orders yet.'),
    'courierOrderDefault': ('Заказ', 'Order'),
    'courierAddressMissing': ('Адрес не указан', 'Address not specified'),
    'courierSlot': ('Время: {slot}', 'Time: {slot}'),
    'courierCustomer': ('Клиент: {name}{phone}', 'Customer: {name}{phone}'),
    'courierCashDue': ('К оплате наличными: {amount}', 'Cash to collect: {amount}'),
    'courierStatus': ('Статус: {status}', 'Status: {status}'),
    'courierStart': ('Начать доставку', 'Start delivery'),
    'courierComplete': ('Подтвердить доставку', 'Confirm delivery'),
    'courierActiveTitle': ('Активные заказы', 'Active orders'),
    'courierHistoryTitle': ('История доставок', 'Delivery history'),
    'courierNoActive': ('Активных заказов нет. Новые назначения появятся здесь.', 'No active orders. New assignments will appear here.'),
    'courierConfirmTitle': ('Подтвердить доставку?', 'Confirm the delivery?'),
    'courierConfirmBody': ('Заказ {number} будет отмечен как доставленный. Отменить это действие нельзя.', 'Order {number} will be marked as delivered. This cannot be undone.'),
    'courierCancelledNote': ('Заказ отменен, доставка не нужна.', 'The order was cancelled: no delivery needed.'),
    'courierPayment': ('Оплата: {method}', 'Payment: {method}'),
    'courierTotal': ('Сумма заказа: {amount}', 'Order total: {amount}'),
    'courierPhoneCopied': ('Телефон скопирован', 'Phone number copied'),
    'courierItemsTitle': ('Состав заказа', 'Items'),
}
