STRINGS = {
    'myOrders': ('Мои заказы', 'My orders'),
    'ordersSignInRequired': ('Авторизуйтесь для просмотра заказов', 'Sign in to view your orders'),
    'ordersLoadFailed': ('Не удалось загрузить заказы. Попробуйте позже.', 'Could not load your orders. Please try later.'),
    'ordersEmptyTitle': ('Пока нет заказов', 'No orders yet'),
    'ordersEmptyBody': ('Когда вы сделаете заказ, он появится здесь.', 'Once you place an order, it will appear here.'),
    'startShopping': ('За покупками', 'Start shopping'),
    'orderNumberFallback': ('Заказ #{id}', 'Order #{id}'),
    'orderCancelled': ('Заказ отменен', 'Order cancelled'),
    'stepCreated': ('Создан', 'Created'),
    'stepWithCourier': ('У курьера', 'With courier'),
    'stepDelivered': ('Доставлен', 'Delivered'),
    'labelAddress': ('Адрес', 'Address'),
    'notSpecified': ('Не указан', 'Not specified'),
    'deliveryTime': ('Время доставки', 'Delivery time'),
    'orderInfoPayment': ('Оплата', 'Payment'),
    'notSpecifiedFem': ('Не указана', 'Not specified'),
    'orderInfoCourier': ('Курьер', 'Courier'),
    'orderInfoCourierPhone': ('Телефон курьера', 'Courier phone'),
    'total': ('Итого', 'Total'),
    'itemDefaultName': ('Товар', 'Item'),
    'quantityLabel': ('Количество: {quantity}', 'Quantity: {quantity}'),
    'hideOrderFailed': ('Не удалось скрыть заказ.', 'Could not hide the order.'),
    'hideOrder': ('Скрыть из списка', 'Hide from list'),
    'orderConfirmedWaiting': ('Вы подтвердили получение. Ожидаем менеджера.', 'You confirmed receipt. Waiting for the manager.'),
    'orderConfirmedToast': ('Вы подтвердили, что всё хорошо!', 'You confirmed that everything is fine!'),
    'orderConfirmFailed': ('Не удалось подтвердить получение.', 'Could not confirm receipt.'),
    'orderConfirmButton': ('Подтвердить, что всё хорошо', 'Confirm everything is fine'),
}
