STRINGS = {
    'reseedTitle': ('Перезалить базу товаров?', 'Reload the product database?'),
    'reseedBody': ('Все текущие товары будут удалены и заменены стартовым каталогом (69 товаров, 9 категорий). Это действие нельзя отменить.', 'All current products will be deleted and replaced with the starter catalog (69 products, 9 categories). This cannot be undone.'),
    'reseedConfirm': ('Перезалить', 'Reload'),
    'reseedLoading': ('Загружаем товары...', 'Loading products...'),
    'reseedDone': ('База товаров успешно обновлена!', 'The product database was updated!'),
    'reseedFailed': ('Не удалось обновить базу товаров.', 'Could not update the product database.'),
    'adminHome': ('Главная', 'Home'),
    'sectionInDevelopment': ('Раздел в разработке', 'This section is under development'),
    'adminDashboardTitle': ('Панель управления', 'Control panel'),
    'adminNewOrders': ('Новые заказы', 'New orders'),
    'adminActive': ('Активные', 'Active'),
    'adminProducts': ('Товары', 'Products'),
    'adminInCatalog': ('В каталоге', 'In the catalog'),
    'adminQuickActions': ('Быстрые действия', 'Quick actions'),
    'adminReseedButton': ('Перезалить базу товаров (Сброс)', 'Reload product database (reset)'),
    'adminReseedHint': ('Загружает стартовый каталог с фотографиями, описанием, составом и пищевой ценностью.', 'Loads the starter catalog with photos, descriptions, ingredients and nutrition facts.'),
    'adminOrdersTitle': ('Управление заказами', 'Order management'),
    'adminNoOrders': ('Нет заказов', 'No orders'),
    'adminNoName': ('Без имени', 'No name'),
    'adminCourierRequired': ('Ошибка: нельзя перевести заказ в статус «В пути» или «Доставлен», пока не назначен курьер!', 'Error: an order cannot be set to “On the way” or “Delivered” until a courier is assigned!'),
    'adminOrderUpdated': ('Заказ успешно обновлен!', 'Order updated successfully!'),
    'adminOrderUpdateFailed': ('Не удалось обновить заказ.', 'Could not update the order.'),
    'adminCustomer': ('Клиент: {name}', 'Customer: {name}'),
    'adminAddress': ('Адрес: {address}', 'Address: {address}'),
    'adminPhone': ('Телефон: {phone}', 'Phone: {phone}'),
    'adminDeliverySlot': ('Время доставки: {slot}', 'Delivery time: {slot}'),
    'adminAmount': ('Сумма: ₽{amount}', 'Amount: ₽{amount}'),
    'adminCourierLabel': ('Курьер:', 'Courier:'),
    'notAssigned': ('Не назначен', 'Not assigned'),
    'adminStatusLabel': ('Статус:', 'Status:'),
}
