// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdsjRPSj_d6rqnv0VkTYqozj9mggUwbE',
    appId: '1:70969291340:web:464aa7206ce3067331fae9',
    messagingSenderId: '70969291340',
    projectId: 'nectar-41848',
    authDomain: 'nectar-41848.firebaseapp.com',
    storageBucket: 'nectar-41848.firebasestorage.app',
    measurementId: 'G-TR33KSG6WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDscRZyca3lBu2ZDJry5jwtJB6kgRGhZcI',
    appId: '1:70969291340:android:19cdd928fc446c5931fae9',
    messagingSenderId: '70969291340',
    projectId: 'nectar-41848',
    storageBucket: 'nectar-41848.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXX2xehAgBmTp0rOccoPA0KLqIaSYbSpU',
    appId: '1:70969291340:ios:9d4feb3c7863a40931fae9',
    messagingSenderId: '70969291340',
    projectId: 'nectar-41848',
    storageBucket: 'nectar-41848.firebasestorage.app',
    iosBundleId: 'com.example.nectar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXX2xehAgBmTp0rOccoPA0KLqIaSYbSpU',
    appId: '1:70969291340:ios:9d4feb3c7863a40931fae9',
    messagingSenderId: '70969291340',
    projectId: 'nectar-41848',
    storageBucket: 'nectar-41848.firebasestorage.app',
    iosBundleId: 'com.example.nectar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfdsjRPSj_d6rqnv0VkTYqozj9mggUwbE',
    appId: '1:70969291340:web:712e450706c8921031fae9',
    messagingSenderId: '70969291340',
    projectId: 'nectar-41848',
    authDomain: 'nectar-41848.firebaseapp.com',
    storageBucket: 'nectar-41848.firebasestorage.app',
    measurementId: 'G-JW3XDJMBG8',
  );

}